@host = https://localhost:8001
@auth = Authorization: Basic user:Test

####

get {{host}}/openapi.json

####

get {{host}}/
{{auth}}

####

get {{host}}/?cleanup=true
{{auth}}

####

get {{host}}/?sync=true
{{auth}}

####

get {{host}}/?like=%25
{{auth}}

####

get {{host}}/?glob=*
{{auth}}

####

get {{host}}/test
{{auth}}

####

get {{host}}/test?effdt=2021-12-14T13:30:53
{{auth}}

####

put {{host}}/test
{{auth}}
Content-Type: application/json

{ "message": "test" }

####

patch {{host}}/test
{{auth}}
Content-Type: application/json-patch+json

[
    { "op": "add", "path": "/description", "value": "Testing 1..2..3.." },
    { "op": "remove", "path": "/message" }
]

####

delete {{host}}/test
{{auth}}

####
